### ISSUE TITLE
Will not compile

### ISSUE THREAD

**Issue by SiriusGen** [ericleb010/hassio-addons#7]
Home Assistant for Linux (Raspberry Pi) version 0.99.2 (as of 22nd Sept 2019) will no longer compile the code. Python version on HA is 3.7.4

Previous release of HA (0.98) was working fine.

Here is the information from the log:

19-09-22 16:17:25 INFO (SyncWorker_11) [hassio.docker.addon] Start build 840189d6/armv7-addon-xboxone:2.0.1
19-09-22 16:17:33 ERROR (SyncWorker_11) [hassio.docker.addon] Can't build 840189d6/armv7-addon-xboxone:2.0.1: The command '/bin/ash -o pipefail -c apk add --no-cache jq gcc musl-dev python3-dev libffi-dev openssl-dev python3 &&     python3 -m ensurepip &&     rm -r /usr/lib/python*/ensurepip &&     pip3 install --upgrade pip setuptools &&     if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi &&     if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi &&     rm -r /root/.cache' returned a non-zero code: 11
19-09-22 16:54:06 ERROR (MainThread) [aiohttp.server] Unhandled exception

EDITED to add log info.

**Comment by ericleb010** [comment]
Thanks for the bug report. I was able to reproduce this on my end; it probably has to do with the dependencies being pulled into the container. Updating the base image from 4.0.3 to 5.0.1 seems to have done the trick.

I'll pull this into the next release shortly.
